services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    volumes:
      - ./client:/app
    ports:
      - 5173:5173
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    volumes:
      - ./server:/app
    ports:
      - 0:3000
    depends_on:
      - redis
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vessel
  redis:  
    image: redis:6.2
    command:
      - /bin/sh
      - -c 
      - redis-server
