// This file is auto-generated by @hey-api/openapi-ts

export const BibleSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    abbreviation: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Abbreviation",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
  },
  type: "object",
  required: ["id", "name"],
  title: "Bible",
} as const;

export const ConfigSchema = {
  properties: {
    default_bible_id: {
      type: "string",
      title: "Default Bible Id",
    },
  },
  type: "object",
  required: ["default_bible_id"],
  title: "Config",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const HealthSchema = {
  properties: {
    status: {
      type: "string",
      title: "Status",
    },
  },
  type: "object",
  required: ["status"],
  title: "Health",
} as const;

export const JournalCreateSchema = {
  properties: {
    title: {
      type: "string",
      title: "Title",
      default: "",
    },
    entry_date: {
      type: "string",
      title: "Entry Date",
      default: "",
    },
    content: {
      type: "string",
      title: "Content",
      default: "",
    },
  },
  type: "object",
  title: "JournalCreate",
} as const;

export const JournalReadSchema = {
  properties: {
    title: {
      type: "string",
      title: "Title",
      default: "",
    },
    entry_date: {
      type: "string",
      title: "Entry Date",
      default: "",
    },
    content: {
      type: "string",
      title: "Content",
      default: "",
    },
    id: {
      type: "integer",
      title: "Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    updated_at: {
      type: "string",
      format: "date-time",
      title: "Updated At",
    },
  },
  type: "object",
  required: ["id", "created_at", "updated_at"],
  title: "JournalRead",
} as const;

export const JournalUpdateSchema = {
  properties: {
    title: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Title",
    },
    entry_date: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Entry Date",
    },
    content: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Content",
    },
  },
  type: "object",
  title: "JournalUpdate",
} as const;

export const TagSchema = {
  properties: {
    tag: {
      type: "string",
      title: "Tag",
    },
    count: {
      type: "integer",
      title: "Count",
    },
  },
  type: "object",
  required: ["tag", "count"],
  title: "Tag",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;

export const VerseSchema = {
  properties: {
    reference: {
      type: "string",
      title: "Reference",
    },
    content: {
      type: "string",
      title: "Content",
    },
  },
  type: "object",
  required: ["reference", "content"],
  title: "Verse",
} as const;

export const VerseHitSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
    },
    reference: {
      type: "string",
      title: "Reference",
    },
    text: {
      type: "string",
      title: "Text",
    },
  },
  type: "object",
  required: ["id", "reference", "text"],
  title: "VerseHit",
} as const;
