// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  ConfigData,
  ConfigResponses,
  CreateJournalData,
  CreateJournalErrors,
  CreateJournalResponses,
  DeleteJournalData,
  DeleteJournalErrors,
  DeleteJournalResponses,
  GetJournalData,
  GetJournalErrors,
  GetJournalResponses,
  GetVerseData,
  GetVerseErrors,
  GetVerseResponses,
  HealthData,
  HealthResponses,
  ListBiblesData,
  ListBiblesErrors,
  ListBiblesResponses,
  ListJournalsData,
  ListJournalsResponses,
  ListTagsData,
  ListTagsResponses,
  SearchVersesData,
  SearchVersesErrors,
  SearchVersesResponses,
  UpdateJournalData,
  UpdateJournalErrors,
  UpdateJournalResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(
  options?: Options<HealthData, ThrowOnError>,
): RequestResult<HealthResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({
    url: "/api/health",
    ...options,
  });

/**
 * Config
 *
 * Client bootstrap: the default Bible version to use before the user picks one.
 */
export const config = <ThrowOnError extends boolean = false>(
  options?: Options<ConfigData, ThrowOnError>,
): RequestResult<ConfigResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ConfigResponses, unknown, ThrowOnError>({
    url: "/api/config",
    ...options,
  });

/**
 * List Bibles
 */
export const listBibles = <ThrowOnError extends boolean = false>(
  options?: Options<ListBiblesData, ThrowOnError>,
): RequestResult<ListBiblesResponses, ListBiblesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ListBiblesResponses,
    ListBiblesErrors,
    ThrowOnError
  >({ url: "/api/bibles", ...options });

/**
 * Search Verses
 *
 * Powers the `@` verse-lookup autocomplete in the journal editor.
 */
export const searchVerses = <ThrowOnError extends boolean = false>(
  options: Options<SearchVersesData, ThrowOnError>,
): RequestResult<SearchVersesResponses, SearchVersesErrors, ThrowOnError> =>
  (options.client ?? client).get<
    SearchVersesResponses,
    SearchVersesErrors,
    ThrowOnError
  >({ url: "/api/bibles/{bible_id}/search", ...options });

/**
 * Get Verse
 */
export const getVerse = <ThrowOnError extends boolean = false>(
  options: Options<GetVerseData, ThrowOnError>,
): RequestResult<GetVerseResponses, GetVerseErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetVerseResponses,
    GetVerseErrors,
    ThrowOnError
  >({ url: "/api/bibles/{bible_id}/verses/{verse_id}", ...options });

/**
 * List Journals
 */
export const listJournals = <ThrowOnError extends boolean = false>(
  options?: Options<ListJournalsData, ThrowOnError>,
): RequestResult<ListJournalsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ListJournalsResponses, unknown, ThrowOnError>(
    { url: "/api/journals", ...options },
  );

/**
 * Create Journal
 */
export const createJournal = <ThrowOnError extends boolean = false>(
  options: Options<CreateJournalData, ThrowOnError>,
): RequestResult<CreateJournalResponses, CreateJournalErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateJournalResponses,
    CreateJournalErrors,
    ThrowOnError
  >({
    url: "/api/journals",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Tags
 *
 * Distinct #idea tags across all entries, powering the `#` autocomplete.
 */
export const listTags = <ThrowOnError extends boolean = false>(
  options?: Options<ListTagsData, ThrowOnError>,
): RequestResult<ListTagsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ListTagsResponses, unknown, ThrowOnError>({
    url: "/api/journals/tags",
    ...options,
  });

/**
 * Delete Journal
 */
export const deleteJournal = <ThrowOnError extends boolean = false>(
  options: Options<DeleteJournalData, ThrowOnError>,
): RequestResult<DeleteJournalResponses, DeleteJournalErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteJournalResponses,
    DeleteJournalErrors,
    ThrowOnError
  >({ url: "/api/journals/{journal_id}", ...options });

/**
 * Get Journal
 */
export const getJournal = <ThrowOnError extends boolean = false>(
  options: Options<GetJournalData, ThrowOnError>,
): RequestResult<GetJournalResponses, GetJournalErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetJournalResponses,
    GetJournalErrors,
    ThrowOnError
  >({ url: "/api/journals/{journal_id}", ...options });

/**
 * Update Journal
 */
export const updateJournal = <ThrowOnError extends boolean = false>(
  options: Options<UpdateJournalData, ThrowOnError>,
): RequestResult<UpdateJournalResponses, UpdateJournalErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateJournalResponses,
    UpdateJournalErrors,
    ThrowOnError
  >({
    url: "/api/journals/{journal_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
