// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  config,
  createJournal,
  deleteJournal,
  getJournal,
  getVerse,
  health,
  listBibles,
  listJournals,
  listTags,
  type Options,
  searchVerses,
  updateJournal,
} from "../sdk.gen";
import type {
  ConfigData,
  ConfigResponse,
  CreateJournalData,
  CreateJournalError,
  CreateJournalResponse,
  DeleteJournalData,
  DeleteJournalError,
  DeleteJournalResponse,
  GetJournalData,
  GetJournalError,
  GetJournalResponse,
  GetVerseData,
  GetVerseError,
  GetVerseResponse,
  HealthData,
  HealthResponse,
  ListBiblesData,
  ListBiblesError,
  ListBiblesResponse,
  ListJournalsData,
  ListJournalsResponse,
  ListTagsData,
  ListTagsResponse,
  SearchVersesData,
  SearchVersesError,
  SearchVersesResponse,
  UpdateJournalData,
  UpdateJournalError,
  UpdateJournalResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthQueryKey = (options?: Options<HealthData>) =>
  createQueryKey("health", options);

/**
 * Health
 */
export const healthOptions = (options?: Options<HealthData>) =>
  queryOptions<
    HealthResponse,
    DefaultError,
    HealthResponse,
    ReturnType<typeof healthQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await health({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthQueryKey(options),
  });

export const configQueryKey = (options?: Options<ConfigData>) =>
  createQueryKey("config", options);

/**
 * Config
 *
 * Client bootstrap: the default Bible version to use before the user picks one.
 */
export const configOptions = (options?: Options<ConfigData>) =>
  queryOptions<
    ConfigResponse,
    DefaultError,
    ConfigResponse,
    ReturnType<typeof configQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await config({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: configQueryKey(options),
  });

export const listBiblesQueryKey = (options?: Options<ListBiblesData>) =>
  createQueryKey("listBibles", options);

/**
 * List Bibles
 */
export const listBiblesOptions = (options?: Options<ListBiblesData>) =>
  queryOptions<
    ListBiblesResponse,
    ListBiblesError,
    ListBiblesResponse,
    ReturnType<typeof listBiblesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listBibles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listBiblesQueryKey(options),
  });

export const searchVersesQueryKey = (options: Options<SearchVersesData>) =>
  createQueryKey("searchVerses", options);

/**
 * Search Verses
 *
 * Powers the `@` verse-lookup autocomplete in the journal editor.
 */
export const searchVersesOptions = (options: Options<SearchVersesData>) =>
  queryOptions<
    SearchVersesResponse,
    SearchVersesError,
    SearchVersesResponse,
    ReturnType<typeof searchVersesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchVerses({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchVersesQueryKey(options),
  });

export const getVerseQueryKey = (options: Options<GetVerseData>) =>
  createQueryKey("getVerse", options);

/**
 * Get Verse
 */
export const getVerseOptions = (options: Options<GetVerseData>) =>
  queryOptions<
    GetVerseResponse,
    GetVerseError,
    GetVerseResponse,
    ReturnType<typeof getVerseQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getVerse({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getVerseQueryKey(options),
  });

export const listJournalsQueryKey = (options?: Options<ListJournalsData>) =>
  createQueryKey("listJournals", options);

/**
 * List Journals
 */
export const listJournalsOptions = (options?: Options<ListJournalsData>) =>
  queryOptions<
    ListJournalsResponse,
    DefaultError,
    ListJournalsResponse,
    ReturnType<typeof listJournalsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listJournals({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listJournalsQueryKey(options),
  });

/**
 * Create Journal
 */
export const createJournalMutation = (
  options?: Partial<Options<CreateJournalData>>,
): UseMutationOptions<
  CreateJournalResponse,
  CreateJournalError,
  Options<CreateJournalData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateJournalResponse,
    CreateJournalError,
    Options<CreateJournalData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createJournal({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listTagsQueryKey = (options?: Options<ListTagsData>) =>
  createQueryKey("listTags", options);

/**
 * List Tags
 *
 * Distinct #idea tags across all entries, powering the `#` autocomplete.
 */
export const listTagsOptions = (options?: Options<ListTagsData>) =>
  queryOptions<
    ListTagsResponse,
    DefaultError,
    ListTagsResponse,
    ReturnType<typeof listTagsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTags({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listTagsQueryKey(options),
  });

/**
 * Delete Journal
 */
export const deleteJournalMutation = (
  options?: Partial<Options<DeleteJournalData>>,
): UseMutationOptions<
  DeleteJournalResponse,
  DeleteJournalError,
  Options<DeleteJournalData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteJournalResponse,
    DeleteJournalError,
    Options<DeleteJournalData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteJournal({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getJournalQueryKey = (options: Options<GetJournalData>) =>
  createQueryKey("getJournal", options);

/**
 * Get Journal
 */
export const getJournalOptions = (options: Options<GetJournalData>) =>
  queryOptions<
    GetJournalResponse,
    GetJournalError,
    GetJournalResponse,
    ReturnType<typeof getJournalQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getJournal({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getJournalQueryKey(options),
  });

/**
 * Update Journal
 */
export const updateJournalMutation = (
  options?: Partial<Options<UpdateJournalData>>,
): UseMutationOptions<
  UpdateJournalResponse,
  UpdateJournalError,
  Options<UpdateJournalData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateJournalResponse,
    UpdateJournalError,
    Options<UpdateJournalData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateJournal({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
