// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Bible
 */
export type Bible = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Abbreviation
   */
  abbreviation?: string | null;
  /**
   * Description
   */
  description?: string | null;
};

/**
 * Config
 */
export type Config = {
  /**
   * Default Bible Id
   */
  default_bible_id: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * Health
 */
export type Health = {
  /**
   * Status
   */
  status: string;
};

/**
 * JournalCreate
 */
export type JournalCreate = {
  /**
   * Title
   */
  title?: string;
  /**
   * Entry Date
   */
  entry_date?: string;
  /**
   * Content
   */
  content?: string;
};

/**
 * JournalRead
 */
export type JournalRead = {
  /**
   * Title
   */
  title?: string;
  /**
   * Entry Date
   */
  entry_date?: string;
  /**
   * Content
   */
  content?: string;
  /**
   * Id
   */
  id: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * JournalUpdate
 */
export type JournalUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Entry Date
   */
  entry_date?: string | null;
  /**
   * Content
   */
  content?: string | null;
};

/**
 * Tag
 */
export type Tag = {
  /**
   * Tag
   */
  tag: string;
  /**
   * Count
   */
  count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * Verse
 */
export type Verse = {
  /**
   * Reference
   */
  reference: string;
  /**
   * Content
   */
  content: string;
};

/**
 * VerseHit
 */
export type VerseHit = {
  /**
   * Id
   */
  id: string;
  /**
   * Reference
   */
  reference: string;
  /**
   * Text
   */
  text: string;
};

export type HealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/health";
};

export type HealthResponses = {
  /**
   * Successful Response
   */
  200: Health;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type ConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/config";
};

export type ConfigResponses = {
  /**
   * Successful Response
   */
  200: Config;
};

export type ConfigResponse = ConfigResponses[keyof ConfigResponses];

export type ListBiblesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Language
     */
    language?: string;
  };
  url: "/api/bibles";
};

export type ListBiblesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListBiblesError = ListBiblesErrors[keyof ListBiblesErrors];

export type ListBiblesResponses = {
  /**
   * Response List Bibles
   *
   * Successful Response
   */
  200: Array<Bible>;
};

export type ListBiblesResponse = ListBiblesResponses[keyof ListBiblesResponses];

export type SearchVersesData = {
  body?: never;
  path: {
    /**
     * Bible Id
     */
    bible_id: string;
  };
  query: {
    /**
     * Query
     *
     * Keyword or reference to search
     */
    query: string;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/bibles/{bible_id}/search";
};

export type SearchVersesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SearchVersesError = SearchVersesErrors[keyof SearchVersesErrors];

export type SearchVersesResponses = {
  /**
   * Response Search Verses
   *
   * Successful Response
   */
  200: Array<VerseHit>;
};

export type SearchVersesResponse =
  SearchVersesResponses[keyof SearchVersesResponses];

export type GetVerseData = {
  body?: never;
  path: {
    /**
     * Bible Id
     */
    bible_id: string;
    /**
     * Verse Id
     */
    verse_id: string;
  };
  query?: never;
  url: "/api/bibles/{bible_id}/verses/{verse_id}";
};

export type GetVerseErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetVerseError = GetVerseErrors[keyof GetVerseErrors];

export type GetVerseResponses = {
  /**
   * Successful Response
   */
  200: Verse;
};

export type GetVerseResponse = GetVerseResponses[keyof GetVerseResponses];

export type ListJournalsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/journals";
};

export type ListJournalsResponses = {
  /**
   * Response List Journals
   *
   * Successful Response
   */
  200: Array<JournalRead>;
};

export type ListJournalsResponse =
  ListJournalsResponses[keyof ListJournalsResponses];

export type CreateJournalData = {
  body: JournalCreate;
  path?: never;
  query?: never;
  url: "/api/journals";
};

export type CreateJournalErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateJournalError = CreateJournalErrors[keyof CreateJournalErrors];

export type CreateJournalResponses = {
  /**
   * Successful Response
   */
  201: JournalRead;
};

export type CreateJournalResponse =
  CreateJournalResponses[keyof CreateJournalResponses];

export type ListTagsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/journals/tags";
};

export type ListTagsResponses = {
  /**
   * Response List Tags
   *
   * Successful Response
   */
  200: Array<Tag>;
};

export type ListTagsResponse = ListTagsResponses[keyof ListTagsResponses];

export type DeleteJournalData = {
  body?: never;
  path: {
    /**
     * Journal Id
     */
    journal_id: number;
  };
  query?: never;
  url: "/api/journals/{journal_id}";
};

export type DeleteJournalErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteJournalError = DeleteJournalErrors[keyof DeleteJournalErrors];

export type DeleteJournalResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteJournalResponse =
  DeleteJournalResponses[keyof DeleteJournalResponses];

export type GetJournalData = {
  body?: never;
  path: {
    /**
     * Journal Id
     */
    journal_id: number;
  };
  query?: never;
  url: "/api/journals/{journal_id}";
};

export type GetJournalErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetJournalError = GetJournalErrors[keyof GetJournalErrors];

export type GetJournalResponses = {
  /**
   * Successful Response
   */
  200: JournalRead;
};

export type GetJournalResponse = GetJournalResponses[keyof GetJournalResponses];

export type UpdateJournalData = {
  body: JournalUpdate;
  path: {
    /**
     * Journal Id
     */
    journal_id: number;
  };
  query?: never;
  url: "/api/journals/{journal_id}";
};

export type UpdateJournalErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateJournalError = UpdateJournalErrors[keyof UpdateJournalErrors];

export type UpdateJournalResponses = {
  /**
   * Successful Response
   */
  200: JournalRead;
};

export type UpdateJournalResponse =
  UpdateJournalResponses[keyof UpdateJournalResponses];
